id: P029F7DFF
initial_creation_type: input
source_metadata:
  Title: Nyāyabinduṭīkāṭippaṇī
  Editor: Theodore Tserbatsky
  Publisher: Academie Imperial des Sciences
  Place of Publication: St.Petersbourg
  Year: '1909'
  nyāyabinduṭīkāṭippaṇī:
    Text Version: ''
    Input Personnel: ''
    Input Date: ''
    Proof Reader: ''
    Supplier: ''
    Sponsor: ''
created_at: '2022-03-08T16:49:12.193557'
last_modified_at: '2022-03-08T16:49:12.193565'
